[package]
name = "rs80"
version = "0.1.0"
authors = ["Cliff L. Biffle <code@cliffle.com>"]

[dependencies]
time = "0.1.40"
lazy_static = "1.0"
clap = "2.32"

[build-dependencies]
combine = "3.3.6"

[profile.release]
debug = true
